### ISSUE TITLE
Bug infinite power

### ISSUE THREAD

**Issue by Victor13youtube** [Xperidia/FNAFGM#2]
I played PvP mode But the energy is always 100%

this is the error that appears in the console: [Five Nights at Freddy's Gamemode] gamemodes / fnafgm / gamemode / init.lua: 995: attempt to index global 'btn' (a nil value)
   1. v - gamemodes / fnafgm / gamemode / init.lua: 995
    2. unknown - moon / includes / modules / hook.lua: 84

**Comment by VictorienXP** [comment]
This is strange : if this error happen I don't understand how the game can start.
I will test SGvsA to be sure and if everything is fine I think you have something conflicting.
I think I will rename some vars and add a better checking system...
Try to found other errors. And copy the result of fnafgm_debug_info when the bug is here.

**Comment by VictorienXP** [comment]
Download and extract https://github.com/Xperidia/FNAFGM/releases/tag/1.081 to garrysmod. And see if you found other errors. Start the night with the map button and copy potential error logs. Reload the map and start the night by typping "!start" and copy potential error logs.
Tell me if the map button create an error and/or if "!start" create an error...

**Comment by VictorienXP** [comment]
Okay everything should be fixed with bb31888

**Comment by VictorienXP** [comment]
I think it's fixed... Nobody talks about this bug I'm closing this.
